; esp-motion-absence-detection
; Boards:
;   - Wemos D1 mini V3.0.0 (ESP8266EX, 4MB flash)
;   - NodeMCU V2/V3 (ESP8266)
;   - ESP-WROOM-32 DEVKIT V1 (ESP32)

[platformio]

; Kies hier het board dat standaard wordt gebruikt.
; Haal de ; weg bij één van de onderstaande regels.

;default_envs = esp32dev
;default_envs = d1_mini
default_envs = esp8266dev


; ---------- Gedeelde instellingen ----------

[env]
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4
    
build_flags =
    -D MQTT_MAX_PACKET_SIZE=512


; ---------- Wemos D1 mini V3.0.0 ----------

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_speed = 921600
board_build.filesystem = littlefs


; ---------- NodeMCU ----------

[env:esp8266dev]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.filesystem = littlefs


; ---------- ESP-WROOM-32 DEVKIT V1 ----------

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs